services:
  app:
    image: yusufhkran/react-trello-academy:4.2
    networks:
      - react-service
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - react-service
networks: 
  react-service:
    driver: bridge
  